import { PrismaClient } from '../src/generated/prisma/index.js'

const prisma = new PrismaClient()

if (process.env.NODE_ENV === 'production') {
  console.log('Seeding is disabled in production.');
  process.exit(0);
}

const mockClasses = [
  {
    title: 'Pasta Pandemonium',
    description: 'Dive into the world of Italian pasta with a twist! Make noodles that would make your nonna giggle.',
    location: 'Rome, Italy',
    address: 'Piazza Navona, 00186 Roma RM, Italy',
    instructorName: 'Giovanni Spaghetti',
    duration: '2h',
    cuisineType: 'Italian',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 75,
    rating: 4.8,
    about: 'Learn the art of pasta making from a true Italian chef. Perfect for beginners!',
    menu: 'Fresh pasta, marinara sauce, garlic bread',
    schedule: 'Every Tuesday and Thursday at 6 PM',
    highlights: 'Hands-on experience, take-home pasta, wine pairing tips',
    additionalInformation: 'Bring your appetite and a container for leftovers!',
  },
  {
    title: 'Sushi Shenanigans',
    description: 'Roll with laughter as you learn the art of sushi making in the heart of Tokyo.',
    location: 'Tokyo, Japan',
    address: '1 Chome-1-2 Oshiage, Sumida City, Tokyo 131-0045, Japan',
    instructorName: 'Aiko Tanaka',
    duration: '2.5h',
    cuisineType: 'Japanese',
    difficulty: 'Intermediate',
    maxStudents: 10,
    price: 120,
    rating: 4.9,
    about: 'Master the delicate art of sushi making with traditional techniques.',
    menu: 'Maki rolls, nigiri, miso soup, green tea',
    schedule: 'Every Saturday at 5 PM',
    highlights: 'Premium fish, bamboo rolling mats, traditional techniques',
    additionalInformation: 'All ingredients provided. No experience necessary!',
  },
  {
    title: 'Taco Tango',
    description: 'Spice up your life with a fiesta of flavors and a side of salsa dancing in Mexico City.',
    location: 'Mexico City, Mexico',
    address: 'Plaza de la Constitución S/N, Centro, Cuauhtémoc, 06000 Ciudad de México, CDMX, Mexico',
    instructorName: 'Carlos Rivera',
    duration: '2h',
    cuisineType: 'Mexican',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 60,
    rating: 4.7,
    about: 'Experience authentic Mexican cuisine with traditional recipes passed down through generations.',
    menu: 'Street tacos, guacamole, salsa verde, horchata',
    schedule: 'Every Friday at 7 PM',
    highlights: 'Fresh tortillas, homemade salsas, tequila tasting',
    additionalInformation: 'Vegetarian options available. Spice levels adjustable.',
  },
  {
    title: 'Croissant Capers',
    description: 'Master the flaky art of croissant making in the city of lights. Oui, chef!',
    location: 'Paris, France',
    address: '5 Av. Anatole France, 75007 Paris, France',
    instructorName: 'Marie Boulanger',
    duration: '3h',
    cuisineType: 'French',
    difficulty: 'Advanced',
    maxStudents: 8,
    price: 95,
    rating: 4.6,
    about: 'Learn the secrets of perfect French pastries from a Parisian baker.',
    menu: 'Butter croissants, pain au chocolat, French coffee',
    schedule: 'Every Sunday at 9 AM',
    highlights: 'Laminated dough technique, butter quality, oven skills',
    additionalInformation: 'Take home your creations. Coffee and tea provided.',
  },
  {
    title: 'Dim Sum Delights',
    description: 'Steam, stuff, and giggle your way through a dim sum adventure in Hong Kong.',
    location: 'Hong Kong, China',
    address: 'Tsim Sha Tsui Promenade, Tsim Sha Tsui, Hong Kong',
    instructorName: 'Li Wei',
    duration: '2.5h',
    cuisineType: 'Chinese',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 110,
    rating: 4.8,
    about: 'Discover the art of dim sum making with authentic Cantonese techniques.',
    menu: 'Har gow, siu mai, char siu bao, jasmine tea',
    schedule: 'Every Wednesday at 6:30 PM',
    highlights: 'Steaming techniques, dumpling folding, tea ceremony',
    additionalInformation: 'All equipment provided. Gluten-free options available.',
  },
  {
    title: 'Bagel Bonanza',
    description: 'Boil, bake, and schmear your way to bagel bliss in New York City.',
    location: 'New York, USA',
    address: '350 5th Ave, New York, NY 10118, USA',
    instructorName: 'Rachel Goldstein',
    duration: '2h',
    cuisineType: 'American',
    difficulty: 'Beginner',
    maxStudents: 16,
    price: 55,
    rating: 4.5,
    about: 'Learn to make authentic New York-style bagels from scratch.',
    menu: 'Everything bagels, cream cheese, lox, coffee',
    schedule: 'Every Saturday at 10 AM',
    highlights: 'Boiling technique, proper kneading, traditional toppings',
    additionalInformation: 'Take home a dozen fresh bagels. Coffee included.',
  },
  {
    title: 'Curry Carnival',
    description: 'Spice up your senses with a whirlwind of Indian curries in Mumbai.',
    location: 'Mumbai, India',
    address: 'Gateway of India, Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India',
    instructorName: 'Priya Singh',
    duration: '2.5h',
    cuisineType: 'Indian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 80,
    rating: 4.7,
    about: 'Master the art of Indian curry making with authentic spices and techniques.',
    menu: 'Butter chicken, naan bread, raita, masala chai',
    schedule: 'Every Thursday at 6 PM',
    highlights: 'Spice blending, tandoor techniques, traditional methods',
    additionalInformation: 'Spice levels adjustable. Vegetarian options available.',
  },
  {
    title: 'Pierogi Party',
    description: 'Stuff, pinch, and boil your way to Polish comfort food in Warsaw.',
    location: 'Warsaw, Poland',
    address: 'Plac Zamkowy, 00-277 Warszawa, Poland',
    instructorName: 'Kasia Nowak',
    duration: '2h',
    cuisineType: 'Polish',
    difficulty: 'Beginner',
    maxStudents: 10,
    price: 65,
    rating: 4.4,
    about: 'Learn to make traditional Polish pierogi with authentic family recipes.',
    menu: 'Potato and cheese pierogi, sour cream, sauerkraut',
    schedule: 'Every Tuesday at 5 PM',
    highlights: 'Dough making, filling preparation, proper sealing',
    additionalInformation: 'Take home frozen pierogi. Traditional music included.',
  },
  {
    title: 'Tapas Tickle',
    description: 'Share laughs and small plates in a lively tapas class in Barcelona.',
    location: 'Barcelona, Spain',
    address: 'La Rambla, 08002 Barcelona, Spain',
    instructorName: 'Miguel Torres',
    duration: '2h',
    cuisineType: 'Spanish',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 90,
    rating: 4.6,
    about: 'Experience the vibrant flavors of Spanish tapas with traditional recipes.',
    menu: 'Patatas bravas, gambas al ajillo, tortilla española, sangria',
    schedule: 'Every Friday at 8 PM',
    highlights: 'Multiple small dishes, Spanish wine pairing, social dining',
    additionalInformation: 'Wine included. Perfect for groups and couples.',
  },
  {
    title: 'Pho-nomenal Fun',
    description: 'Simmer, slurp, and smile as you make authentic pho in Hanoi.',
    location: 'Hanoi, Vietnam',
    address: '1 Hàng Trống, Hoàn Kiếm, Hà Nội, Vietnam',
    instructorName: 'Nguyen Minh',
    duration: '2.5h',
    cuisineType: 'Vietnamese',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 70,
    rating: 4.5,
    about: 'Learn to make authentic Vietnamese pho with traditional broth techniques.',
    menu: 'Beef pho, fresh herbs, bean sprouts, Vietnamese coffee',
    schedule: 'Every Sunday at 11 AM',
    highlights: 'Broth making, herb preparation, noodle cooking',
    additionalInformation: 'Vegetarian pho option available. Take home broth recipe.',
  },
  {
    title: 'Ramen Revolution',
    description: 'Master the art of Japanese ramen from broth to bowl in Osaka.',
    location: 'Osaka, Japan',
    address: '1-1-1 Umeda, Kita Ward, Osaka, Japan',
    instructorName: 'Kenji Nakamura',
    duration: '3h',
    cuisineType: 'Japanese',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 100,
    rating: 4.8,
    about: 'Learn to make authentic ramen noodles and broth from scratch.',
    menu: 'Shoyu ramen, gyoza, green tea',
    schedule: 'Every Monday at 6 PM',
    highlights: 'Broth simmering, noodle making, toppings bar',
    additionalInformation: 'Aprons provided. Vegetarian options available.',
  },
  {
    title: 'BBQ Bootcamp',
    description: 'Grill like a pro with classic American BBQ techniques in Austin.',
    location: 'Austin, USA',
    address: '123 BBQ Lane, Austin, TX, USA',
    instructorName: 'Billy Ray',
    duration: '4h',
    cuisineType: 'American',
    difficulty: 'Advanced',
    maxStudents: 20,
    price: 150,
    rating: 4.9,
    about: 'Master the grill with slow-cooked meats and signature sauces.',
    menu: 'Brisket, ribs, cornbread, coleslaw',
    schedule: 'Every Saturday at 2 PM',
    highlights: 'Smoker demo, sauce tasting, grill safety',
    additionalInformation: 'Outdoor event. Bring your own cooler.',
  },
  {
    title: 'Vegan Vittles',
    description: 'Explore plant-based cuisine with creative vegan recipes in Berlin.',
    location: 'Berlin, Germany',
    address: 'Veggie St. 42, 10115 Berlin, Germany',
    instructorName: 'Greta Weiss',
    duration: '2h',
    cuisineType: 'Vegan',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 70,
    rating: 4.7,
    about: 'Discover delicious vegan meals that everyone will love.',
    menu: 'Vegan burgers, cashew cheese, raw desserts',
    schedule: 'Every Thursday at 5 PM',
    highlights: 'Plant-based proteins, dairy alternatives, meal planning',
    additionalInformation: 'All recipes gluten-free. Take-home booklet included.',
  },
  {
    title: 'Moroccan Magic',
    description: 'Spice up your kitchen with Moroccan tagines and couscous in Marrakech.',
    location: 'Marrakech, Morocco',
    address: 'Souk St., Medina, Marrakech, Morocco',
    instructorName: 'Fatima Zahra',
    duration: '2.5h',
    cuisineType: 'Moroccan',
    difficulty: 'Intermediate',
    maxStudents: 10,
    price: 90,
    rating: 4.8,
    about: 'Experience the flavors of Morocco with traditional spices and techniques.',
    menu: 'Chicken tagine, couscous, mint tea',
    schedule: 'Every Wednesday at 7 PM',
    highlights: 'Spice blending, slow cooking, Moroccan hospitality',
    additionalInformation: 'Halal ingredients. Recipes provided.',
  },
  {
    title: 'Pizza Perfection',
    description: 'Craft the perfect Neapolitan pizza in Naples with a wood-fired oven.',
    location: 'Naples, Italy',
    address: 'Via Pizza 8, 80100 Napoli NA, Italy',
    instructorName: 'Luigi Romano',
    duration: '2h',
    cuisineType: 'Italian',
    difficulty: 'Beginner',
    maxStudents: 18,
    price: 80,
    rating: 4.9,
    about: 'Learn to make pizza dough, sauce, and bake in a real wood-fired oven.',
    menu: 'Margherita pizza, calzone, tiramisu',
    schedule: 'Every Friday at 6 PM',
    highlights: 'Dough tossing, sauce secrets, oven skills',
    additionalInformation: 'Aprons and chef hats provided.',
  },
  {
    title: 'French Bistro Basics',
    description: 'Cook classic French bistro dishes in Lyon with a local chef.',
    location: 'Lyon, France',
    address: 'Rue de la Cuisine 12, 69001 Lyon, France',
    instructorName: 'Jean-Pierre Dubois',
    duration: '2.5h',
    cuisineType: 'French',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 100,
    rating: 4.7,
    about: 'Master French classics like coq au vin and crème brûlée.',
    menu: 'Coq au vin, ratatouille, crème brûlée',
    schedule: 'Every Tuesday at 7 PM',
    highlights: 'Wine pairing, sauce making, plating',
    additionalInformation: 'Wine included. Recipes in English and French.',
  },
  {
    title: 'Tapas & Flamenco',
    description: 'Enjoy Spanish tapas and a flamenco show in Seville.',
    location: 'Seville, Spain',
    address: 'Calle de Tapas 5, 41001 Sevilla, Spain',
    instructorName: 'Isabella Martinez',
    duration: '3h',
    cuisineType: 'Spanish',
    difficulty: 'Beginner',
    maxStudents: 20,
    price: 95,
    rating: 4.8,
    about: 'Cook and share classic tapas while enjoying live flamenco.',
    menu: 'Chorizo al vino, tortilla, sangria',
    schedule: 'Every Saturday at 8 PM',
    highlights: 'Live music, group cooking, Spanish wines',
    additionalInformation: 'Show included. Group discounts available.',
  },
  {
    title: 'Thai Street Food',
    description: 'Recreate the flavors of Bangkok street food in this hands-on class.',
    location: 'Bangkok, Thailand',
    address: 'Soi Food 9, Bangkok, Thailand',
    instructorName: 'Somsak Chaiyaporn',
    duration: '2h',
    cuisineType: 'Thai',
    difficulty: 'Beginner',
    maxStudents: 16,
    price: 75,
    rating: 4.7,
    about: 'Make pad thai, green curry, and mango sticky rice like a local.',
    menu: 'Pad thai, green curry, mango sticky rice',
    schedule: 'Every Thursday at 6 PM',
    highlights: 'Wok skills, spice balancing, street food culture',
    additionalInformation: 'Spice levels adjustable. All ages welcome.',
  },
  {
    title: 'Nordic Baking',
    description: 'Bake Scandinavian breads and pastries in Stockholm.',
    location: 'Stockholm, Sweden',
    address: 'Bagerigatan 3, 111 44 Stockholm, Sweden',
    instructorName: 'Anna Lindgren',
    duration: '2.5h',
    cuisineType: 'Nordic',
    difficulty: 'Intermediate',
    maxStudents: 10,
    price: 85,
    rating: 4.6,
    about: 'Learn to bake cinnamon buns, rye bread, and more.',
    menu: 'Kanelbullar, rye bread, cardamom cake',
    schedule: 'Every Sunday at 10 AM',
    highlights: 'Dough kneading, proofing, Nordic flavors',
    additionalInformation: 'Coffee and fika included.',
  },
  {
    title: 'Seafood Soirée',
    description: 'Prepare fresh seafood dishes on the coast of Sydney.',
    location: 'Sydney, Australia',
    address: 'Harbor Rd 7, Sydney, NSW, Australia',
    instructorName: 'Liam O\'Connor',
    duration: '3h',
    cuisineType: 'Australian',
    difficulty: 'Advanced',
    maxStudents: 14,
    price: 130,
    rating: 4.9,
    about: 'Cook with the freshest seafood and learn expert techniques.',
    menu: 'Grilled barramundi, prawn cocktail, pavlova',
    schedule: 'Every Friday at 5 PM',
    highlights: 'Fish filleting, shellfish prep, wine pairing',
    additionalInformation: 'Seafood allergies: notify in advance.',
  },
  {
    title: 'Middle Eastern Mezze',
    description: 'Create a spread of mezze dishes in Tel Aviv.',
    location: 'Tel Aviv, Israel',
    address: 'Shuk HaCarmel, Tel Aviv, Israel',
    instructorName: 'Yossi Cohen',
    duration: '2h',
    cuisineType: 'Middle Eastern',
    difficulty: 'Beginner',
    maxStudents: 18,
    price: 80,
    rating: 4.7,
    about: 'Make hummus, falafel, and more with local ingredients.',
    menu: 'Hummus, falafel, tabbouleh, pita',
    schedule: 'Every Monday at 7 PM',
    highlights: 'Chickpea prep, spice blends, pita baking',
    additionalInformation: 'Vegan friendly. All ages welcome.',
  },
  {
    title: 'Korean BBQ Night',
    description: 'Grill and share Korean BBQ favorites in Seoul.',
    location: 'Seoul, South Korea',
    address: 'Gangnam-daero 123, Seoul, South Korea',
    instructorName: 'Min-Jun Kim',
    duration: '2.5h',
    cuisineType: 'Korean',
    difficulty: 'Intermediate',
    maxStudents: 16,
    price: 120,
    rating: 4.8,
    about: 'Experience the fun of Korean BBQ with all the sides.',
    menu: 'Bulgogi, kimchi, lettuce wraps, soju',
    schedule: 'Every Saturday at 6 PM',
    highlights: 'Table grilling, marinade secrets, banchan variety',
    additionalInformation: 'Aprons provided. Group bookings welcome.',
  },
  {
    title: 'Indian Sweets Workshop',
    description: 'Make classic Indian desserts in New Delhi.',
    location: 'New Delhi, India',
    address: 'Sweet St. 5, New Delhi, India',
    instructorName: 'Rohit Sharma',
    duration: '2h',
    cuisineType: 'Indian',
    difficulty: 'Beginner',
    maxStudents: 14,
    price: 60,
    rating: 4.6,
    about: 'Learn to make gulab jamun, jalebi, and more.',
    menu: 'Gulab jamun, jalebi, rasgulla',
    schedule: 'Every Sunday at 4 PM',
    highlights: 'Sugar syrup, dough shaping, frying tips',
    additionalInformation: 'Allergy info: contains dairy and nuts.',
  },
  {
    title: 'Greek Island Feast',
    description: 'Cook Mediterranean classics on the island of Santorini.',
    location: 'Santorini, Greece',
    address: 'Oia Village, Santorini, Greece',
    instructorName: 'Eleni Papadopoulos',
    duration: '2.5h',
    cuisineType: 'Greek',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 95,
    rating: 4.8,
    about: 'Prepare Greek favorites with fresh island ingredients.',
    menu: 'Moussaka, Greek salad, baklava',
    schedule: 'Every Friday at 7 PM',
    highlights: 'Olive oil tasting, phyllo dough, island wines',
    additionalInformation: 'Vegetarian options available. Wine included.',
  },
  {
    title: 'Brazilian Churrasco',
    description: 'Grill meats and enjoy a Brazilian BBQ in Rio.',
    location: 'Rio de Janeiro, Brazil',
    address: 'Copacabana Beach, Rio de Janeiro, Brazil',
    instructorName: 'João Silva',
    duration: '3h',
    cuisineType: 'Brazilian',
    difficulty: 'Advanced',
    maxStudents: 20,
    price: 140,
    rating: 4.9,
    about: 'Experience the flavors of Brazil with authentic churrasco.',
    menu: 'Picanha, farofa, caipirinha',
    schedule: 'Every Saturday at 5 PM',
    highlights: 'Meat skewers, open fire, Brazilian cocktails',
    additionalInformation: 'Outdoor event. Rain or shine.',
  },
  {
    title: 'Lebanese Mezze',
    description: 'Prepare a variety of Lebanese mezze in Beirut.',
    location: 'Beirut, Lebanon',
    address: 'Hamra St., Beirut, Lebanon',
    instructorName: 'Maya Haddad',
    duration: '2h',
    cuisineType: 'Lebanese',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 85,
    rating: 4.7,
    about: 'Make tabbouleh, baba ganoush, and more.',
    menu: 'Tabbouleh, baba ganoush, kibbeh',
    schedule: 'Every Wednesday at 6 PM',
    highlights: 'Herb chopping, mezze plating, pita baking',
    additionalInformation: 'Vegan friendly. All ages welcome.',
  },
  {
    title: 'Swiss Fondue Night',
    description: 'Enjoy a cozy night of cheese fondue in Zurich.',
    location: 'Zurich, Switzerland',
    address: 'Fonduegasse 1, 8001 Zurich, Switzerland',
    instructorName: 'Hans Keller',
    duration: '2h',
    cuisineType: 'Swiss',
    difficulty: 'Beginner',
    maxStudents: 10,
    price: 90,
    rating: 4.8,
    about: 'Learn the secrets to perfect Swiss fondue.',
    menu: 'Cheese fondue, crusty bread, white wine',
    schedule: 'Every Friday at 7 PM',
    highlights: 'Cheese selection, fondue etiquette, wine pairing',
    additionalInformation: 'Gluten-free bread available.',
  },
  {
    title: 'Ethiopian Injera Experience',
    description: 'Bake and share injera and stews in Addis Ababa.',
    location: 'Addis Ababa, Ethiopia',
    address: 'Meskel Square, Addis Ababa, Ethiopia',
    instructorName: 'Selam Tesfaye',
    duration: '2.5h',
    cuisineType: 'Ethiopian',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 80,
    rating: 4.7,
    about: 'Make injera and traditional Ethiopian stews.',
    menu: 'Injera, doro wat, lentil stew',
    schedule: 'Every Sunday at 1 PM',
    highlights: 'Fermentation, spice blends, communal eating',
    additionalInformation: 'Vegan options available. Spicy food warning.',
  },
  {
    title: 'Russian Dumpling Day',
    description: 'Make pelmeni and borscht in Moscow.',
    location: 'Moscow, Russia',
    address: 'Red Square, Moscow, Russia',
    instructorName: 'Olga Ivanova',
    duration: '2h',
    cuisineType: 'Russian',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 70,
    rating: 4.6,
    about: 'Learn to make Russian dumplings and soup.',
    menu: 'Pelmeni, borscht, rye bread',
    schedule: 'Every Saturday at 11 AM',
    highlights: 'Dough rolling, soup simmering, Russian tea',
    additionalInformation: 'Recipes provided. Family friendly.',
  },
  {
    title: 'Turkish Breakfast Feast',
    description: 'Prepare a traditional Turkish breakfast in Istanbul.',
    location: 'Istanbul, Turkey',
    address: 'Sultanahmet, Istanbul, Turkey',
    instructorName: 'Ahmet Demir',
    duration: '2h',
    cuisineType: 'Turkish',
    difficulty: 'Beginner',
    maxStudents: 16,
    price: 75,
    rating: 4.7,
    about: 'Make simit, menemen, and more for a Turkish breakfast.',
    menu: 'Simit, menemen, Turkish tea',
    schedule: 'Every Sunday at 9 AM',
    highlights: 'Bread baking, egg dishes, tea brewing',
    additionalInformation: 'Vegetarian friendly. Tea included.',
  },
  {
    title: 'Argentinian Asado',
    description: 'Grill meats and enjoy an Argentinian BBQ in Buenos Aires.',
    location: 'Buenos Aires, Argentina',
    address: 'Parrilla Ave, Buenos Aires, Argentina',
    instructorName: 'Santiago Lopez',
    duration: '3h',
    cuisineType: 'Argentinian',
    difficulty: 'Advanced',
    maxStudents: 18,
    price: 135,
    rating: 4.9,
    about: 'Experience the tradition of Argentinian asado.',
    menu: 'Short ribs, chimichurri, Malbec wine',
    schedule: 'Every Saturday at 6 PM',
    highlights: 'Fire management, meat carving, wine pairing',
    additionalInformation: 'Outdoor event. Rain or shine.',
  },
  {
    title: 'Vietnamese Spring Rolls',
    description: 'Roll and dip fresh spring rolls in Ho Chi Minh City.',
    location: 'Ho Chi Minh City, Vietnam',
    address: 'Ben Thanh Market, Ho Chi Minh City, Vietnam',
    instructorName: 'Lan Pham',
    duration: '1.5h',
    cuisineType: 'Vietnamese',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 60,
    rating: 4.6,
    about: 'Learn to make fresh and fried Vietnamese spring rolls.',
    menu: 'Goi cuon, cha gio, nuoc cham',
    schedule: 'Every Friday at 3 PM',
    highlights: 'Rice paper rolling, dipping sauces, fresh herbs',
    additionalInformation: 'Vegetarian options available. All ages welcome.',
  },
  {
    title: 'Caribbean Cooking',
    description: 'Cook jerk chicken and tropical sides in Kingston.',
    location: 'Kingston, Jamaica',
    address: 'Beach Rd, Kingston, Jamaica',
    instructorName: 'Marley Brown',
    duration: '2h',
    cuisineType: 'Caribbean',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 85,
    rating: 4.7,
    about: 'Spice up your kitchen with Caribbean flavors.',
    menu: 'Jerk chicken, rice and peas, plantains',
    schedule: 'Every Saturday at 1 PM',
    highlights: 'Spice rubs, grilling, tropical drinks',
    additionalInformation: 'Spicy food warning. Recipes provided.',
  },
  {
    title: 'Persian Feast',
    description: 'Prepare a Persian feast with saffron and pomegranates in Tehran.',
    location: 'Tehran, Iran',
    address: 'Grand Bazaar, Tehran, Iran',
    instructorName: 'Shirin Azadi',
    duration: '2.5h',
    cuisineType: 'Persian',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 100,
    rating: 4.8,
    about: 'Cook with Persian spices and learn traditional recipes.',
    menu: 'Fesenjan, saffron rice, Persian tea',
    schedule: 'Every Thursday at 7 PM',
    highlights: 'Saffron use, pomegranate prep, tea ceremony',
    additionalInformation: 'Halal ingredients. Tea included.',
  },
  {
    title: 'Belgian Waffle Workshop',
    description: 'Make and top Belgian waffles in Brussels.',
    location: 'Brussels, Belgium',
    address: 'Waffle St. 10, 1000 Brussels, Belgium',
    instructorName: 'Sophie Dubois',
    duration: '1.5h',
    cuisineType: 'Belgian',
    difficulty: 'Beginner',
    maxStudents: 10,
    price: 65,
    rating: 4.7,
    about: 'Learn to make classic Belgian waffles and toppings.',
    menu: 'Waffles, chocolate sauce, whipped cream',
    schedule: 'Every Sunday at 10 AM',
    highlights: 'Batter mixing, waffle irons, topping bar',
    additionalInformation: 'Gluten-free options available.',
  },
  {
    title: 'South African Braai',
    description: 'Experience a traditional braai in Cape Town.',
    location: 'Cape Town, South Africa',
    address: 'Table Mountain Rd, Cape Town, South Africa',
    instructorName: 'Sipho Nkosi',
    duration: '3h',
    cuisineType: 'South African',
    difficulty: 'Advanced',
    maxStudents: 16,
    price: 120,
    rating: 4.8,
    about: 'Grill meats and sides in a South African style.',
    menu: 'Boerewors, pap, chakalaka',
    schedule: 'Every Saturday at 4 PM',
    highlights: 'Fire building, meat grilling, local beers',
    additionalInformation: 'Outdoor event. Family friendly.',
  },
  {
    title: 'Canadian Maple Treats',
    description: 'Bake with maple syrup in Montreal.',
    location: 'Montreal, Canada',
    address: 'Maple Ave, Montreal, Canada',
    instructorName: 'Claire Tremblay',
    duration: '2h',
    cuisineType: 'Canadian',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 70,
    rating: 4.6,
    about: 'Make classic Canadian desserts with real maple syrup.',
    menu: 'Maple tarts, sugar pie, maple cookies',
    schedule: 'Every Sunday at 2 PM',
    highlights: 'Maple syrup tasting, pastry making, Canadian trivia',
    additionalInformation: 'Nut-free options available.',
  },
  {
    title: 'Filipino Fiesta',
    description: 'Cook traditional Filipino dishes in Manila.',
    location: 'Manila, Philippines',
    address: 'Rizal Park, Manila, Philippines',
    instructorName: 'Maria Santos',
    duration: '2.5h',
    cuisineType: 'Filipino',
    difficulty: 'Intermediate',
    maxStudents: 16,
    price: 75,
    rating: 4.7,
    about: 'Learn to make adobo, sinigang, and other Filipino favorites.',
    menu: 'Chicken adobo, sinigang, halo-halo',
    schedule: 'Every Saturday at 3 PM',
    highlights: 'Sour soup making, pork dishes, tropical desserts',
    additionalInformation: 'Pork-free options available.',
  },
  {
    title: 'Egyptian Street Food',
    description: 'Make koshari and falafel in Cairo.',
    location: 'Cairo, Egypt',
    address: 'Khan el-Khalili, Cairo, Egypt',
    instructorName: 'Ahmed Hassan',
    duration: '2h',
    cuisineType: 'Egyptian',
    difficulty: 'Beginner',
    maxStudents: 14,
    price: 65,
    rating: 4.6,
    about: 'Experience the flavors of Egyptian street food.',
    menu: 'Koshari, falafel, ful medames',
    schedule: 'Every Friday at 6 PM',
    highlights: 'Rice and lentil dishes, street food culture',
    additionalInformation: 'Vegan friendly. All ages welcome.',
  },
  {
    title: 'Hungarian Goulash',
    description: 'Cook hearty Hungarian dishes in Budapest.',
    location: 'Budapest, Hungary',
    address: 'Heroes Square, Budapest, Hungary',
    instructorName: 'Istvan Nagy',
    duration: '2.5h',
    cuisineType: 'Hungarian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 85,
    rating: 4.7,
    about: 'Learn to make goulash and other Hungarian classics.',
    menu: 'Beef goulash, paprikash, dobos torte',
    schedule: 'Every Wednesday at 7 PM',
    highlights: 'Paprika use, slow cooking, Hungarian wines',
    additionalInformation: 'Wine included. Recipes provided.',
  },
  {
    title: 'Peruvian Ceviche',
    description: 'Make fresh ceviche and Peruvian dishes in Lima.',
    location: 'Lima, Peru',
    address: 'Miraflores, Lima, Peru',
    instructorName: 'Carlos Mendoza',
    duration: '2h',
    cuisineType: 'Peruvian',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 90,
    rating: 4.8,
    about: 'Learn to make authentic Peruvian ceviche and sides.',
    menu: 'Ceviche, causa, pisco sour',
    schedule: 'Every Tuesday at 6 PM',
    highlights: 'Fish preparation, citrus marinades, Peruvian cocktails',
    additionalInformation: 'Seafood allergies: notify in advance.',
  },
  {
    title: 'Polish Pierogi Party',
    description: 'Make traditional Polish dumplings in Krakow.',
    location: 'Krakow, Poland',
    address: 'Main Market Square, Krakow, Poland',
    instructorName: 'Katarzyna Kowalski',
    duration: '2.5h',
    cuisineType: 'Polish',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 70,
    rating: 4.6,
    about: 'Learn to make pierogi with various fillings.',
    menu: 'Pierogi, borscht, apple strudel',
    schedule: 'Every Sunday at 1 PM',
    highlights: 'Dough making, filling preparation, traditional music',
    additionalInformation: 'Vegetarian options available.',
  },
  {
    title: 'Turkish Kebab Workshop',
    description: 'Make authentic Turkish kebabs in Istanbul.',
    location: 'Istanbul, Turkey',
    address: 'Grand Bazaar, Istanbul, Turkey',
    instructorName: 'Mehmet Yilmaz',
    duration: '2h',
    cuisineType: 'Turkish',
    difficulty: 'Beginner',
    maxStudents: 18,
    price: 80,
    rating: 4.7,
    about: 'Learn to make various types of Turkish kebabs.',
    menu: 'Adana kebab, doner, baklava',
    schedule: 'Every Thursday at 7 PM',
    highlights: 'Meat preparation, grilling techniques, Turkish tea',
    additionalInformation: 'Halal ingredients. Tea included.',
  },
  {
    title: 'Indonesian Rijsttafel',
    description: 'Prepare a traditional Indonesian feast in Jakarta.',
    location: 'Jakarta, Indonesia',
    address: 'Old Town, Jakarta, Indonesia',
    instructorName: 'Sari Wijaya',
    duration: '3h',
    cuisineType: 'Indonesian',
    difficulty: 'Advanced',
    maxStudents: 14,
    price: 110,
    rating: 4.8,
    about: 'Learn to make multiple Indonesian dishes for a rijsttafel.',
    menu: 'Nasi goreng, satay, gado-gado',
    schedule: 'Every Saturday at 5 PM',
    highlights: 'Rice dishes, peanut sauce, spice pastes',
    additionalInformation: 'Peanut allergies: notify in advance.',
  },
  {
    title: 'Czech Beer & Food',
    description: 'Cook Czech dishes and learn about beer in Prague.',
    location: 'Prague, Czech Republic',
    address: 'Old Town Square, Prague, Czech Republic',
    instructorName: 'Jan Novak',
    duration: '2.5h',
    cuisineType: 'Czech',
    difficulty: 'Intermediate',
    maxStudents: 16,
    price: 95,
    rating: 4.7,
    about: 'Make traditional Czech dishes and learn about Czech beer.',
    menu: 'Goulash, dumplings, beer',
    schedule: 'Every Friday at 6 PM',
    highlights: 'Beer pairing, dumpling making, Czech culture',
    additionalInformation: 'Beer included. Age 21+ for alcohol.',
  },
  {
    title: 'Malaysian Street Food',
    description: 'Cook Malaysian street food favorites in Kuala Lumpur.',
    location: 'Kuala Lumpur, Malaysia',
    address: 'Petaling Street, Kuala Lumpur, Malaysia',
    instructorName: 'Ahmad bin Abdullah',
    duration: '2h',
    cuisineType: 'Malaysian',
    difficulty: 'Beginner',
    maxStudents: 15,
    price: 75,
    rating: 4.6,
    about: 'Learn to make nasi lemak and other Malaysian street food.',
    menu: 'Nasi lemak, satay, teh tarik',
    schedule: 'Every Monday at 6 PM',
    highlights: 'Coconut rice, peanut sauce, Malaysian tea',
    additionalInformation: 'Halal ingredients. Spice levels adjustable.',
  },
  {
    title: 'Romanian Comfort Food',
    description: 'Make traditional Romanian dishes in Bucharest.',
    location: 'Bucharest, Romania',
    address: 'Old Town, Bucharest, Romania',
    instructorName: 'Elena Popescu',
    duration: '2.5h',
    cuisineType: 'Romanian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 70,
    rating: 4.5,
    about: 'Learn to make sarmale and other Romanian comfort foods.',
    menu: 'Sarmale, mamaliga, cozonac',
    schedule: 'Every Sunday at 2 PM',
    highlights: 'Cabbage rolling, polenta making, traditional desserts',
    additionalInformation: 'Vegetarian options available.',
  },
  {
    title: 'Chilean Seafood',
    description: 'Cook fresh Chilean seafood in Santiago.',
    location: 'Santiago, Chile',
    address: 'Central Market, Santiago, Chile',
    instructorName: 'Pablo Rodriguez',
    duration: '2.5h',
    cuisineType: 'Chilean',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 100,
    rating: 4.7,
    about: 'Learn to cook with fresh Chilean seafood and local ingredients.',
    menu: 'Chupe de mariscos, ceviche, pisco sour',
    schedule: 'Every Friday at 7 PM',
    highlights: 'Seafood preparation, Chilean wines, coastal cuisine',
    additionalInformation: 'Seafood allergies: notify in advance.',
  },
  {
    title: 'Bulgarian Banitsa',
    description: 'Make traditional Bulgarian pastries in Sofia.',
    location: 'Sofia, Bulgaria',
    address: 'Alexander Nevsky Square, Sofia, Bulgaria',
    instructorName: 'Viktoria Petrova',
    duration: '2h',
    cuisineType: 'Bulgarian',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 65,
    rating: 4.6,
    about: 'Learn to make banitsa and other Bulgarian pastries.',
    menu: 'Banitsa, shopska salad, rakia',
    schedule: 'Every Saturday at 10 AM',
    highlights: 'Phyllo dough, cheese filling, Bulgarian brandy',
    additionalInformation: 'Vegetarian friendly. Brandy included.',
  },
  {
    title: 'Colombian Arepas',
    description: 'Make Colombian arepas and traditional dishes in Bogota.',
    location: 'Bogota, Colombia',
    address: 'La Candelaria, Bogota, Colombia',
    instructorName: 'Isabella Morales',
    duration: '2h',
    cuisineType: 'Colombian',
    difficulty: 'Beginner',
    maxStudents: 16,
    price: 70,
    rating: 4.7,
    about: 'Learn to make arepas and other Colombian favorites.',
    menu: 'Arepas, bandeja paisa, aguardiente',
    schedule: 'Every Thursday at 6 PM',
    highlights: 'Corn dough, grilling, Colombian spirits',
    additionalInformation: 'Gluten-free options available.',
  },
  {
    title: 'Croatian Coastal Cuisine',
    description: 'Cook Mediterranean-inspired Croatian dishes in Split.',
    location: 'Split, Croatia',
    address: 'Diocletian Palace, Split, Croatia',
    instructorName: 'Marko Kovac',
    duration: '2.5h',
    cuisineType: 'Croatian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 90,
    rating: 4.8,
    about: 'Learn to make Croatian coastal dishes with fresh ingredients.',
    menu: 'Black risotto, grilled fish, Croatian wine',
    schedule: 'Every Tuesday at 7 PM',
    highlights: 'Seafood risotto, wine pairing, coastal techniques',
    additionalInformation: 'Wine included. Seafood allergies: notify.',
  },
  {
    title: 'Slovakian Dumplings',
    description: 'Make traditional Slovakian dumplings in Bratislava.',
    location: 'Bratislava, Slovakia',
    address: 'Old Town, Bratislava, Slovakia',
    instructorName: 'Jana Svobodova',
    duration: '2h',
    cuisineType: 'Slovakian',
    difficulty: 'Beginner',
    maxStudents: 10,
    price: 60,
    rating: 4.5,
    about: 'Learn to make bryndzove halusky and other Slovakian dishes.',
    menu: 'Bryndzove halusky, kapustnica, Slovakian beer',
    schedule: 'Every Wednesday at 6 PM',
    highlights: 'Potato dumplings, sheep cheese, traditional beer',
    additionalInformation: 'Beer included. Vegetarian options.',
  },
  {
    title: 'Ecuadorian Ceviche',
    description: 'Make Ecuadorian ceviche and coastal dishes in Quito.',
    location: 'Quito, Ecuador',
    address: 'Old Town, Quito, Ecuador',
    instructorName: 'Diego Torres',
    duration: '2h',
    cuisineType: 'Ecuadorian',
    difficulty: 'Beginner',
    maxStudents: 14,
    price: 75,
    rating: 4.6,
    about: 'Learn to make Ecuadorian ceviche and traditional sides.',
    menu: 'Ceviche, encebollado, canelazo',
    schedule: 'Every Friday at 6 PM',
    highlights: 'Citrus marinades, fish preparation, Ecuadorian drinks',
    additionalInformation: 'Seafood allergies: notify in advance.',
  },
  {
    title: 'Lithuanian Cepelinai',
    description: 'Make traditional Lithuanian dumplings in Vilnius.',
    location: 'Vilnius, Lithuania',
    address: 'Old Town, Vilnius, Lithuania',
    instructorName: 'Rasa Jankauskaite',
    duration: '2.5h',
    cuisineType: 'Lithuanian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 70,
    rating: 4.6,
    about: 'Learn to make cepelinai and other Lithuanian specialties.',
    menu: 'Cepelinai, kugelis, gira',
    schedule: 'Every Sunday at 1 PM',
    highlights: 'Potato dumplings, traditional kvass, Lithuanian culture',
    additionalInformation: 'Vegetarian options available.',
  },
  {
    title: 'Uruguayan Asado',
    description: 'Experience Uruguayan BBQ in Montevideo.',
    location: 'Montevideo, Uruguay',
    address: 'Rambla, Montevideo, Uruguay',
    instructorName: 'Gabriel Fernandez',
    duration: '3h',
    cuisineType: 'Uruguayan',
    difficulty: 'Advanced',
    maxStudents: 16,
    price: 120,
    rating: 4.8,
    about: 'Learn the art of Uruguayan asado with local meats.',
    menu: 'Asado, chimichurri, Tannat wine',
    schedule: 'Every Saturday at 5 PM',
    highlights: 'Fire management, meat selection, Uruguayan wines',
    additionalInformation: 'Outdoor event. Wine included.',
  },
  {
    title: 'Latvian Rye Bread',
    description: 'Bake traditional Latvian rye bread in Riga.',
    location: 'Riga, Latvia',
    address: 'Old Town, Riga, Latvia',
    instructorName: 'Ilze Berzina',
    duration: '2h',
    cuisineType: 'Latvian',
    difficulty: 'Beginner',
    maxStudents: 10,
    price: 65,
    rating: 4.5,
    about: 'Learn to bake traditional Latvian rye bread.',
    menu: 'Rye bread, sklandrausis, kvass',
    schedule: 'Every Saturday at 10 AM',
    highlights: 'Sourdough starter, rye flour, traditional kvass',
    additionalInformation: 'Gluten-free options available.',
  },
  {
    title: 'Paraguayan Chipa',
    description: 'Make traditional Paraguayan bread in Asuncion.',
    location: 'Asuncion, Paraguay',
    address: 'Plaza de los Heroes, Asuncion, Paraguay',
    instructorName: 'Maria Gonzalez',
    duration: '2h',
    cuisineType: 'Paraguayan',
    difficulty: 'Beginner',
    maxStudents: 12,
    price: 60,
    rating: 4.6,
    about: 'Learn to make chipa and other Paraguayan breads.',
    menu: 'Chipa, sopa paraguaya, terere',
    schedule: 'Every Sunday at 9 AM',
    highlights: 'Cheese bread, corn flour, traditional drinks',
    additionalInformation: 'Gluten-free options available.',
  },
  {
    title: 'Estonian Smoked Fish',
    description: 'Cook with smoked fish in Tallinn.',
    location: 'Tallinn, Estonia',
    address: 'Old Town, Tallinn, Estonia',
    instructorName: 'Kati Saar',
    duration: '2.5h',
    cuisineType: 'Estonian',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 85,
    rating: 4.7,
    about: 'Learn to cook with traditional Estonian smoked fish.',
    menu: 'Smoked salmon, black bread, Estonian beer',
    schedule: 'Every Friday at 6 PM',
    highlights: 'Smoking techniques, rye bread, Baltic cuisine',
    additionalInformation: 'Beer included. Seafood allergies: notify.',
  },
  {
    title: 'Bolivian Saltenas',
    description: 'Make traditional Bolivian pastries in La Paz.',
    location: 'La Paz, Bolivia',
    address: 'Witches Market, La Paz, Bolivia',
    instructorName: 'Carmen Quispe',
    duration: '2h',
    cuisineType: 'Bolivian',
    difficulty: 'Intermediate',
    maxStudents: 14,
    price: 70,
    rating: 4.6,
    about: 'Learn to make saltenas and other Bolivian specialties.',
    menu: 'Saltenas, api, singani',
    schedule: 'Every Saturday at 11 AM',
    highlights: 'Pastry making, Bolivian spirits, traditional drinks',
    additionalInformation: 'Vegetarian options available.',
  },
  {
    title: 'Slovenian Potica',
    description: 'Bake traditional Slovenian nut roll in Ljubljana.',
    location: 'Ljubljana, Slovenia',
    address: 'Preseren Square, Ljubljana, Slovenia',
    instructorName: 'Ana Novak',
    duration: '2.5h',
    cuisineType: 'Slovenian',
    difficulty: 'Advanced',
    maxStudents: 10,
    price: 80,
    rating: 4.7,
    about: 'Learn to make potica and other Slovenian pastries.',
    menu: 'Potica, kremna rezina, Slovenian wine',
    schedule: 'Every Sunday at 10 AM',
    highlights: 'Nut rolling, cream cake, Slovenian wines',
    additionalInformation: 'Nut allergies: notify in advance.',
  },
  {
    title: 'Venezuelan Arepas',
    description: 'Make Venezuelan arepas and traditional dishes in Caracas.',
    location: 'Caracas, Venezuela',
    address: 'Plaza Bolivar, Caracas, Venezuela',
    instructorName: 'Luis Rodriguez',
    duration: '2h',
    cuisineType: 'Venezuelan',
    difficulty: 'Beginner',
    maxStudents: 16,
    price: 75,
    rating: 4.6,
    about: 'Learn to make arepas and other Venezuelan favorites.',
    menu: 'Arepas, pabellon criollo, papelon con limon',
    schedule: 'Every Thursday at 6 PM',
    highlights: 'Corn dough, shredded beef, traditional drinks',
    additionalInformation: 'Gluten-free options available.',
  },
  {
    title: 'Maltese Pastizzi',
    description: 'Make traditional Maltese pastries in Valletta.',
    location: 'Valletta, Malta',
    address: 'Republic Street, Valletta, Malta',
    instructorName: 'Joseph Borg',
    duration: '2h',
    cuisineType: 'Maltese',
    difficulty: 'Intermediate',
    maxStudents: 12,
    price: 70,
    rating: 4.5,
    about: 'Learn to make pastizzi and other Maltese specialties.',
    menu: 'Pastizzi, ftira, Kinnie',
    schedule: 'Every Saturday at 10 AM',
    highlights: 'Phyllo pastry, ricotta filling, Maltese soft drinks',
    additionalInformation: 'Vegetarian options available.',
  },
]

async function main() {
  for (const mock of mockClasses) {
    await prisma.class.create({
      data: mock
    })
  }
  console.log('Database seeded with mock classes.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 